from datetime import datetime
from sqlalchemy import text

from backend.database import engine


def get_documents():
    """
    Load uploaded document metadata from SQLite.
    """

    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT
                    document_id,
                    file_name,
                    document_type,
                    upload_time,
                    chunk_count,
                    status
                FROM documents
                ORDER BY document_id ASC
            """)
        ).fetchall()

    return [
        {
            "document_id": row[0],
            "file_name": row[1],
            "document_type": row[2],
            "upload_time": row[3],
            "chunk_count": row[4],
            "status": row[5]
        }
        for row in rows
    ]


def get_risks():
    """
    Load extracted risks from SQLite.
    """

    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT
                    risk_id,
                    risk_category,
                    severity,
                    evidence,
                    explanation,
                    confidence,
                    human_review_required,
                    created_at
                FROM risks
                ORDER BY
                    CASE severity
                        WHEN 'High' THEN 1
                        WHEN 'Medium' THEN 2
                        WHEN 'Low' THEN 3
                        ELSE 4
                    END,
                    risk_id ASC
            """)
        ).fetchall()

    return [
        {
            "risk_id": row[0],
            "risk_category": row[1],
            "severity": row[2],
            "evidence": row[3],
            "explanation": row[4],
            "confidence": row[5],
            "human_review_required": bool(row[6]),
            "created_at": row[7]
        }
        for row in rows
    ]


def get_findings():
    """
    Load generated audit findings from SQLite.
    """

    with engine.connect() as conn:
        rows = conn.execute(
            text("""
                SELECT
                    finding_id,
                    risk_id,
                    title,
                    condition,
                    criteria_text,
                    cause,
                    impact,
                    recommendation,
                    severity,
                    created_at
                FROM findings
                ORDER BY
                    CASE severity
                        WHEN 'High' THEN 1
                        WHEN 'Medium' THEN 2
                        WHEN 'Low' THEN 3
                        ELSE 4
                    END,
                    finding_id ASC
            """)
        ).fetchall()

    return [
        {
            "finding_id": row[0],
            "risk_id": row[1],
            "title": row[2],
            "condition": row[3],
            "criteria_text": row[4],
            "cause": row[5],
            "impact": row[6],
            "recommendation": row[7],
            "severity": row[8],
            "created_at": row[9]
        }
        for row in rows
    ]


def count_by_field(items, field_name):
    """
    Count records by a selected field.
    Example: count risks by severity or category.
    """

    counts = {}

    for item in items:
        key = item.get(field_name) or "Unknown"
        counts[key] = counts.get(key, 0) + 1

    return counts


def generate_markdown_report():
    """
    Generate a Markdown audit summary report from SQLite data.
    """

    documents = get_documents()
    risks = get_risks()
    findings = get_findings()

    severity_counts = count_by_field(risks, "severity")
    category_counts = count_by_field(risks, "risk_category")

    high_risks = severity_counts.get("High", 0)
    medium_risks = severity_counts.get("Medium", 0)
    low_risks = severity_counts.get("Low", 0)

    human_review_count = sum(
        1 for risk in risks
        if risk.get("human_review_required")
    )

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report_lines = []

    report_lines.append("# AuditIQ Audit Summary Report")
    report_lines.append("")
    report_lines.append(f"**Generated At:** {generated_at}")
    report_lines.append("")
    report_lines.append("---")
    report_lines.append("")

    report_lines.append("## 1. Executive Summary")
    report_lines.append("")
    report_lines.append(
        "This report summarizes audit documents reviewed, risks extracted, "
        "and audit findings generated by AuditIQ. The outputs are AI-assisted "
        "and should be reviewed by a human auditor before use in any formal audit process."
    )
    report_lines.append("")
    report_lines.append(f"- Documents reviewed: **{len(documents)}**")
    report_lines.append(f"- Risks detected: **{len(risks)}**")
    report_lines.append(f"- Findings generated: **{len(findings)}**")
    report_lines.append(f"- High severity risks: **{high_risks}**")
    report_lines.append(f"- Medium severity risks: **{medium_risks}**")
    report_lines.append(f"- Low severity risks: **{low_risks}**")
    report_lines.append(f"- Risks requiring human review: **{human_review_count}**")
    report_lines.append("")

    report_lines.append("## 2. Documents Reviewed")
    report_lines.append("")

    if documents:
        report_lines.append("| Document ID | File Name | Type | Chunks | Status | Upload Time |")
        report_lines.append("|---|---|---|---:|---|---|")

        for doc in documents:
            report_lines.append(
                f"| {doc['document_id']} "
                f"| {doc['file_name']} "
                f"| {doc['document_type']} "
                f"| {doc['chunk_count']} "
                f"| {doc['status']} "
                f"| {doc['upload_time']} |"
            )
    else:
        report_lines.append("No documents were found in the database.")

    report_lines.append("")

    report_lines.append("## 3. Risk Summary")
    report_lines.append("")

    report_lines.append("### Risks by Severity")
    report_lines.append("")

    if severity_counts:
        report_lines.append("| Severity | Count |")
        report_lines.append("|---|---:|")

        for severity, count in severity_counts.items():
            report_lines.append(f"| {severity} | {count} |")
    else:
        report_lines.append("No risks were found.")

    report_lines.append("")

    report_lines.append("### Risks by Category")
    report_lines.append("")

    if category_counts:
        report_lines.append("| Risk Category | Count |")
        report_lines.append("|---|---:|")

        for category, count in category_counts.items():
            report_lines.append(f"| {category} | {count} |")
    else:
        report_lines.append("No risk categories were found.")

    report_lines.append("")

    report_lines.append("## 4. Detailed Risks")
    report_lines.append("")

    if risks:
        for risk in risks:
            report_lines.append(f"### Risk {risk['risk_id']}: {risk['risk_category']}")
            report_lines.append("")
            report_lines.append(f"- **Severity:** {risk['severity']}")
            report_lines.append(f"- **Confidence:** {risk['confidence']}")
            report_lines.append(f"- **Human Review Required:** {risk['human_review_required']}")
            report_lines.append(f"- **Evidence:** {risk['evidence']}")
            report_lines.append(f"- **Explanation:** {risk['explanation']}")
            report_lines.append("")
    else:
        report_lines.append("No detailed risks were found.")

    report_lines.append("")

    report_lines.append("## 5. Generated Audit Findings")
    report_lines.append("")

    if findings:
        for finding in findings:
            report_lines.append(f"### Finding {finding['finding_id']}: {finding['title']}")
            report_lines.append("")
            report_lines.append(f"- **Related Risk ID:** {finding['risk_id']}")
            report_lines.append(f"- **Severity:** {finding['severity']}")
            report_lines.append(f"- **Condition:** {finding['condition']}")
            report_lines.append(f"- **Criteria:** {finding['criteria_text']}")
            report_lines.append(f"- **Cause:** {finding['cause']}")
            report_lines.append(f"- **Risk / Impact:** {finding['impact']}")
            report_lines.append(f"- **Recommendation:** {finding['recommendation']}")
            report_lines.append("")
    else:
        report_lines.append("No audit findings were generated yet.")

    report_lines.append("")

    report_lines.append("## 6. Human Review Notes")
    report_lines.append("")
    report_lines.append(
        "AuditIQ is designed to assist auditors by summarizing evidence, identifying possible risk signals, "
        "and drafting findings. It does not replace professional judgment. All extracted risks and generated "
        "findings should be validated against source documents before use."
    )
    report_lines.append("")

    report_lines.append("## 7. Suggested Next Steps")
    report_lines.append("")
    report_lines.append("- Validate high severity risks against source evidence.")
    report_lines.append("- Confirm whether missing approvals or delayed reviews are true control exceptions.")
    report_lines.append("- Review generated findings for accuracy, completeness, and audit wording.")
    report_lines.append("- Add remediation owners, due dates, and management responses if this becomes a fuller workflow.")
    report_lines.append("")

    report_content = "\n".join(report_lines)

    return {
        "report": report_content,
        "generated_at": generated_at,
        "document_count": len(documents),
        "risk_count": len(risks),
        "finding_count": len(findings)
    }